## NumPy

In [58]:
# Import numpy:
import numpy as np

## 1. DataTypes & Attributes

In [59]:
# Numpy's main datatype is ndarray(n dimentional array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [60]:
type(a1)

numpy.ndarray

In [61]:
a2 = np.array([[1, 2, 3.3],
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a1.shape

(3,)

In [65]:
a2.shape

(2, 3)

In [66]:
a3.shape

(2, 3, 3)

In [67]:
# Number of dimentions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [68]:
# DataType
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [69]:
# Count the elements in the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [70]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [71]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [72]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [73]:
sample_array.dtype

dtype('int32')

In [74]:
# Array with 1 (by default its a float)
ones = np.ones((2,3))

In [75]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
ones.dtype

dtype('float64')

In [77]:
type(ones)

numpy.ndarray

In [78]:
# Array with 0 (setting it to be integers)
zeros = np.zeros((2,3), dtype = int)

In [79]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [80]:
# arguments --> start, stop (not included), steps
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [81]:
# Array with random numbers --> strat, stop, size
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[1, 1, 5, 3, 2],
       [0, 4, 8, 7, 1],
       [4, 9, 3, 6, 7]])

In [82]:
random_array.size

15

In [83]:
random_array.shape

(3, 5)

In [84]:
# Array with random numbers in between 0.0 and 1.0 --> shape/size
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.63847702, 0.86288872, 0.63662654],
       [0.99929706, 0.51778008, 0.32761664],
       [0.09877324, 0.5667664 , 0.21520794],
       [0.01179079, 0.29921532, 0.03897743],
       [0.97621382, 0.55145308, 0.07171621]])

In [85]:
random_array_2.shape

(5, 3)

In [86]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.34006782, 0.24290239, 0.10735082],
       [0.77033058, 0.35060155, 0.18764274],
       [0.91265269, 0.86114826, 0.39889823],
       [0.54633644, 0.45037544, 0.69359919],
       [0.21384609, 0.3237989 , 0.73989292]])

## 3. NumPy Rnadom Seed

In [87]:
# Pseudo-random numbers --> Creates random numbers but keeps the aligned with the seed(keeps them the same)
# seed ca be any number
np.random.seed(seed=999999)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[1, 7, 4],
       [6, 9, 6],
       [1, 1, 0],
       [3, 0, 6],
       [4, 7, 3]])

In [88]:
random_array_4.shape

(5, 3)

In [89]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [90]:
# The numbers change since it's a different cell
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 4. Viewing Arrays and Matrices

In [91]:
random_array_4

array([[1, 7, 4],
       [6, 9, 6],
       [1, 1, 0],
       [3, 0, 6],
       [4, 7, 3]])

In [92]:
# Find the unique numbers in the array
np.unique(random_array_4)

array([0, 1, 3, 4, 6, 7, 9])

In [93]:
a1

array([1, 2, 3])

In [94]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [95]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [96]:
a1[0]

1

In [97]:
a2[0]

array([1. , 2. , 3.3])

In [98]:
a3.shape

(2, 3, 3)

In [99]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [101]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [102]:
# Check: Shape and Dimention
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [103]:
a4[1][1][0]

array([9, 6, 8, 1, 5])

In [104]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## 5. Manipulating and Comparing Arrays

## Arithmatic

In [105]:
a1

array([1, 2, 3])

In [106]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [107]:
# Add
a1 + ones

array([2., 3., 4.])

In [108]:
# Subtract
a1 - ones

array([0., 1., 2.])

In [109]:
# Multiply
a1 * ones

array([1., 2., 3.])

In [110]:
a1

array([1, 2, 3])

In [111]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [112]:
# a1 multiplies to every row in a2
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [113]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

General Broadcasting Rules:
1. They are equal
2. One of them is 1D

In [114]:
# Error (General Broadcasting Rule applies)
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# Reshape a2 to be compatible with a3
# Search: "How to reshape numpy array"
new_a2 = a2.reshape(2, 1, 3)
new_a2



In [ ]:
#Divide
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
# Square
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
# Modulus Operation
a1 % 2

In [ ]:
a2 % 2

In [ ]:
# Euler's number (approximately 2.718) to the power of every number in the array
np.exp(a1)

In [ ]:
# Compute the natural logarithm of the values
np.log(a1)



## Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
# Python method sum() --> gives back the sum of the list
sum(listy_list)

In [ ]:
a1

In [ ]:
sum(a1)

In [ ]:
# NumPy method sum()
np.sum(a1)

Use Python's methods('sum()') on Python datatypes and use NumPy methods on NumPy
arrays('np.sum()')

In [ ]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
# Magic function "%"
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
a2

In [ ]:
# Mean
np.mean(a2)

In [ ]:
# Maximum 'np.max()' & Minimum 'np.min()'
np.max(a2), np.min(a2)

In [ ]:
# Standard Deviation 'np.std()'
np.std(a2)

In [ ]:
# Variance 'np.var()'
np.var(a2)

In [ ]:
# Square Root 'np.sqrt()'
np.sqrt(np.var(a2))

In [ ]:
# Demo of STD and VAR 
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array,), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & Transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
# Reshape '.reshape()'
a2.reshape(2, 3, 1)

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape, a3

In [ ]:
a2_reshape * a3

In [ ]:
#Transpose = switches the axis'
a2, a2.shape

In [ ]:
a2.T

In [ ]:
a2.shape

In [ ]:
a3.shape

In [ ]:
a3.T.shape

## Dot Productm

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot Product --> the inside numbers must mach --> (3, 3) and (3, 2) would work
np.dot(mat2, mat1)

In [ ]:
# Transpose  mat1
mat2.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot Product Example (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

In [ ]:
# Create a weekly_sales DatFrame out of sales_amount
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut Butter", "Cashew butter"])

weekly_sales

In [ ]:
# Create the prices
prices = np.array([10, 8, 12])
prices

In [ ]:
# Create butter_prices DataFrame out of prices --> change shape
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Prices ($)"],
                             columns=["Almond butter", "Peanut Butter", "Cashew butter"])
butter_prices

In [ ]:
# Shapes aren't aligned --> use transpose(.T)
total_sales = prices.dot(sales_amounts.T)
total_sales

                                       Create daily_sales

In [ ]:
butter_prices.shape, weekly_sales.shape

In [ ]:
# Flip weekly_sales so we have the same number on the inside --> use transpose(.T)
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales

In [ ]:
# Get this on to the right hand side of the weekly_sales DataFrame
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

## Comparison Operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 == a2

## 6. Sorting arrays

In [ ]:
random_array = np.random.randint(10, size=(3, 5))
random_array

In [ ]:
# Sort by rows --> np.sort()
np.sort(random_array)

In [ ]:
# Arg sort --> sorting by index (1 = index 2,  5 = index 3.....)
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
# Index of the minimun number
np.argmin(a1)

In [ ]:
# Index of the maximum number
np.argmax(a1)

In [ ]:
random_array

In [ ]:
# 2D+ arrays index of maximum/minimum number --> use: (axis=0) for columns
np.argmax(random_array, axis=0), np.argmin(random_array, axis=0)

In [ ]:
# 2D+ arrays index of maximum/minimum number --> use: (axis=1) for rows
np.argmax(random_array, axis=1), np.argmin(random_array, axis=0)

## 7. Practical Example - Numpy

                             Import image:   <img src="images/panda.png"/> ---> esc, markdown

<img src="images/panda.png"/>

In [ ]:
# Turn an image in to a NumPy array
from matplotlib.image import imread   #package from matplotlib "imread" which reads images

panda = imread("images/panda.png")
print(type(panda))

In [ ]:
panda.size, panda.shape, panda.ndim

In [ ]:
panda[:5]

<img src="images/car-photo.png"/>

In [ ]:
car = imread("images/car-photo.png")
print(type(car))

In [ ]:
car[:1]

<img src="images/dog-photo.png"/>

In [ ]:
dog = imread("images/dog-photo.png")
print(type(dog))

In [ ]:
dog[:10]